name: "Build APK"

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: "Build release APK"
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@a391126403df92c6a0a3988a829dd47f79b89ed7
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: "Rename APK"
        run: |
          VERSION_NAME="$(jq -r ".elements[0].versionName" "app/build/outputs/apk/release/output-metadata.json")"
          echo "Version name: $VERSION_NAME" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          cat "app/build/outputs/apk/release/output-metadata.json" >> "$GITHUB_STEP_SUMMARY"
          echo >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk "app/build/outputs/apk/release/Downloader-Navi-v$VERSION_NAME.apk"

      - name: "Upload APK"
        uses: actions/upload-artifact@v7
        with:
          name: Downloader-Navi
          path: app/build/outputs/apk/release/Downloader-Navi-*.apk
          archive: false
